### ISSUE TITLE
Error with product system, empty exported file

### ISSUE THREAD

**Issue by Husamalbaghdadi** [GreenDelta/openlca-python-tutorial#16]
Thank you very much for your valuable work,

may I ask you please for the reason of the empty exported csv file using Python API with openlca?
when I try to create and export (a product system) the results as csv file

https://github.com/GreenDelta/openlca-python-tutorial/blob/master/product_systems.md 
 I also used Eclipse as an IDE just for checking the syntax, but there where no error with the syntax!

Best regards,
Husam

**Comment by msrocka** [comment]
I updated the example to be compatible to the current version of the openLCA API

**Comment by Husamalbaghdadi** [comment]
Thank you very much! that was really helpful!

**Comment by Husamalbaghdadi** [comment]
May I ask you, please:
How could I specify the quantity?
and how to specify whether it is unit or system process?
Thank you very much and best regards,
Husam

**Comment by msrocka** [comment]
The quantitative reference of the product system is set in the `createProductSystem` function of the example (e.g. `system.targetAmount = qRef.amount` sets the amount of the product system to the amount of the quantitative reference of the reference process).

The product system builder (function `buildProductSystem`) can be configured to prefer system or unit processes in the linking process (`setLinkingMethod(ProcessType.LCI_RESULT)` see the [ProductSystemBuilder class](https://github.com/GreenDelta/olca-modules/blob/master/olca-core/src/main/java/org/openlca/core/matrix/ProductSystemBuilder.java))

**Comment by Husamalbaghdadi** [comment]
Dear Michael,

I updated the version of openlca to the current version (1.9) according to the upgrading of the databases. Some of the databases are not working with the old version of openlca.
Now I have a problem with creating a product using Python. Could you please update the code within the current versions of openlca (1.9).

thank you very much for your support,
Best regards,
Husam
